events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Tráfico para el Frontend de Angular
        location / {
            proxy_pass http://monitor-front:4200;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # ──► ESTO ES LO QUE SE AGREGA: Soporte de WebSockets para Vite
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Tráfico para la API de Spring Boot
        location /api/ {
            proxy_pass http://monitor-back:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
